### ISSUE TITLE
Layout issue with local actions links

### ISSUE THREAD

**Issue by pgoddardmobomo** [mobomo/lark#21]
The links in the local actions block (block-lark-local-actions), are overlapping vertically and not readable. Suggest making these inline.

This is visible on any admin page that has multiple links in the local actions block, such as configuring a webform.

![Screen Shot 2020-08-12 at 6 59 40 AM](https://user-images.githubusercontent.com/69162966/90026857-b89b8500-dc6c-11ea-96fe-5b0b55c9b792.png)

**Comment by carwin** [comment]
Resolved in the 1.0.0-beta5 tag
