### ISSUE TITLE
Update the Logo Images styling

### ISSUE THREAD

**Issue by smustgrave** [mobomo/lark#28]
Hoping to make it so if the user changes the logo the image will fit the region

**Comment by carwin** [comment]
@smustgrave can we get some more information about this issue? So far it's a little vague.

**Comment by smustgrave** [comment]
Hey @carwin sorry for the delay.  This is so we can we trade out the logo from the setting and the size be consistent between the default logo and whatever is uploaded.

**Comment by carwin** [comment]
I believe we merged a PR that addresses this, so I'll close it. If that's a mistake just let me know and we'll re-open.
