### ISSUE TITLE
Remove dependency on the search module

### ISSUE THREAD

**Issue by zenphp** [mobomo/lark#47]
Enforcing a dependency on the search module will often conflict with site requirements that do not make use of that module and will duplicate work being done via the SeachAPI module and it's associated modules (Solr, Elastic, Lunr...).

An admin search, if needed should be implemented as an optional set of modules that can make use of the above as needed.  

Tasks:

- [x] Remove the search block from the configuration and layouts.
- [x] Remove the dependency on Search from the info file.

**Comment by smustgrave** [comment]
@zenphp I can take a look at this if you want?  Besides deleting the file should there be some update that would remove the block if the theme is already installed?

**Comment by carwin** [comment]
@smustgrave I don't think we need to include any kind of update hook to remove the block. This issue is only an issue if the Search module is not enabled, which wouldn't be the case if you had the block placed I don't think.
