### ISSUE TITLE
Fix styling for buttons in text editor page

### ISSUE THREAD

**Issue by smustgrave** [mobomo/lark#59]
<img width="915" alt="Screen Shot 2020-10-07 at 6 28 26 PM" src="https://user-images.githubusercontent.com/10660823/95394640-e991e200-08ca-11eb-873a-80ddfc11582c.png">

**Comment by carwin** [comment]
I'm not sure if this is still an issue. Assigning to @leo-mobomo to confirm and fix if necessary.

**Comment by Goeken** [comment]
This no longer seems to be an issue.
<img width="1036" alt="Screen Shot 2021-03-08 at 7 55 14 AM" src="https://user-images.githubusercontent.com/25854106/110345655-ae175300-7fe3-11eb-9e22-45400abf65e2.png">
