### ISSUE TITLE
Style pager, use the recent log messages page for reference.

### ISSUE THREAD

**Issue by carwin** [mobomo/lark#9]

**Comment by smustgrave** [comment]
@carwin  what do you think of this?
<img width="1344" alt="Screen Shot 2020-10-01 at 1 41 29 PM" src="https://user-images.githubusercontent.com/10660823/94844194-e048d700-03eb-11eb-9a88-9a539331ed8c.png">

**Comment by carwin** [comment]
:+1: - I merged the pull request you'd opened for this one. I'll go ahead and close this issue. Thanks!
